name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
      
    - run: |
        docker build -t ghcr.io/trab_xastre/trabalho_xastre/demovideo:latest -f Dockerfile .
        docker tag ghcr.io/trab_xastre/Trabalho_Xastre/demovideo:latest ghcr.io/trab_xastre/Trabalho_Xastre/demovideo:${{ github.sha }}
    - run: |
        docker push ghcr.io/trab_xastre/Trabalho_Xastre/demovideo:latest
        docker push ghcr.io/trab_xastre/Trabalho_Xastre/demovideo:${{ github.sha }}
