name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
      
    - run: |
        docker build -t meu_sql:5.7 -f Dockerfile .
        docker tag meu_sql:5.7  meu_sql:${{ github.sha }}
    - run: |
        docker push ghcr.io/meu_sql:5.7
        docker push ghcr.io/meu_sql:${{ github.sha }}
