- name: build image
  id: build-image
  uses: redhat-actions/buildah-build@v2
  with:
    image: myuser/myimage
    tags: latest
    dockerfiles: |
      ./Dockerfile

    name: push image to ghcr.io
    uses: redhat-actions/push-to-registry@v2
    with:
    image: ${{ steps.build-image.outputs.image }}
    tags: ${{ steps.build-image.outputs.tags }}
    registry: ghcr.io
    username: ${{ secrets.GH_PACKAGES_USER  }}
    password: ${{ secrets.GH_PACKAGES_TOKEN }}
